/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title SPI communication via QSPI
 * \abstract A QSPI module configured as SPI master sends five bytes to another QSPI module which is configured as SPI slave.
 * \description QSPI2 is configured in master mode and used to send five bytes to QSPI3 configured in slave mode.
 *              The received data is read by the CPU and compared against the transmitted data. Port pin 13.3,
 *              to which LED D110 is connected, indicates the successful transfer.
 *
 * \name SPI_CPU_1_KIT_TC397_TFT
 * \version V1.0.1
 * \board APPLICATION KIT TC3X7 V2.0, KIT_A2G_TC397_5V_TFT, TC39xXX_B-Step
 * \keywords AURIX, Communication, Master, QSPI, SPI, SPI_CPU_1, Slave
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_SPI_CPU_1_KIT_TC397_TFT-TR-v01_00_01-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC39B_iLLD_UM_1_0_1_12_1.chm
 * \lastUpdated 2020-12-18
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "SPI_CPU.h"
#include "Bsp.h"
#include "MatrixEve2Conf.h"
#include "Eve2_81x.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* Initialize the QSPI module, the TC397 EVB LED and the RST pin*/
    initPeripherals();

   // FT81x_Init(DISPLAY_101, BOARD_EVE4, TOUCH_TPC);
    FT81x_Init_VisualC(DISPLAY_70I_WG, BOARD_EVE4, TOUCH_TPC);

    ClearScreen();
    MakeScreen_MatrixOrbital(30);         //Draw the Matrix Orbital Screen

    //Backlight dimming
    //wr8(REG_PWM_DUTY + RAM_REG, 128);                 // Backlight 100% brightness
    //wr8(REG_PWM_DUTY + RAM_REG, 64);                  // Backlight 50% brightness
    wr8(REG_PWM_DUTY + RAM_REG, 32);                  // Backlight 25% brightness

    //this loop continuously checks if the blue dot on the LCD is pressed and changes its size if it is.
    uint8_t pressed = 0;
    while (1)
    {
        uint8_t Tag = rd8(REG_TOUCH_TAG + RAM_REG);                    // Check for touches
        switch (Tag)
        {
            case 1:
                if (!pressed)
                {
                    MakeScreen_MatrixOrbital(120); //Blue dot is 120 when not touched
                    pressed = 1;
                }
                break;
            default:
                if (pressed)
                {
                    pressed = 0;
                    MakeScreen_MatrixOrbital(30); //Blue dot size is 30 when not touched
                }
                break;
        }
    }


    while(1)
    {
    }
}

